name: abelliz_essentials
description: "A collection of reusable Flutter components, utilities, and interfaces to accelerate development across projects."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  mobkit_dashed_border: ^0.0.6

flutter:
  uses-material-design: true
